; THIS CODE CONVERTS A STRING TO THIS REVERSED PATTERN
 CODE SEGMENT
    ASSUME CS:CODE, DS:CODE
    
    
    LEA SI, STRING ; LOAD EFFECTIVE ADDRESS OF THE STRING ARRAY
    LEA DI, STRING
    XOR AX, AX
    L1: CMP [SI], 24H ; COMPARING WITH $
    JE L2
    ADD AX, 1
    ADD SI, 1
    JMP L1 ; THIS SECTION DETERMINES THE WORD LENGTH OF THE STRING
    
    L2:
    MOV BX, 2
    DIV BX
    MOV CX, AX
    DEC SI ; NUMBER OF LOOPS TO BE PERFORMED IS HALF OF THE WORD LENGTH
    
    LEVEL: MOV BL, [DI] ; EXCHANGING VALUES BETWEEN FIRST AND LAST 
    XCHG [SI], BL
    MOV [DI], BL
    DEC SI
    INC DI
    LOOP LEVEL
    
    HLT  
                
        STRING DB "BANGLADESH","$" ; STRING DEFINED AS A BYTE TYPE VARIABLE, $ MARKING THE TERMINATION OF THE STRING   
    END


